'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class imprimir

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''radImpresion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radImpresion As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''btnConfirmar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnConfirmar As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''btnCancelar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelar As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''txtDatosCategoria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDatosCategoria As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTituloCategoria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTituloCategoria As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''GridViewDataCategoria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewDataCategoria As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''txtDatosTodas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDatosTodas As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTituloTodas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTituloTodas As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''GridViewDataTodas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewDataTodas As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''txtTituloTodas0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTituloTodas0 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''GridViewDataTodas0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewDataTodas0 As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''txtTituloTodas1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTituloTodas1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''GridViewDataTodas1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewDataTodas1 As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''txtTituloTodas2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTituloTodas2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''GridViewDataTodas2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewDataTodas2 As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''txtTituloTodas3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTituloTodas3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''GridViewDataTodas3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewDataTodas3 As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''txtTituloTodas4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTituloTodas4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''GridViewDataTodas4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewDataTodas4 As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''txtTituloTodas5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTituloTodas5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''GridViewDataTodas5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewDataTodas5 As Global.System.Web.UI.WebControls.GridView
End Class
